#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

killall -q nitrogen
# Wait until the processes have been shut down
while pgrep -u $UID -x nitrogen >/dev/null; do sleep 1; done
nitrogen --restore &
killall -q picom 
# Wait until the processes have been shut down
while pgrep -u $UID -x nitrogen >/dev/null; do sleep 1; done
picom &
~/.config/polybar/launch.sh &
nm-applet &
killall pa-applet && pa-applet &
dunst &

my_laptop_external_monitor=$(xrandr --query | grep 'HDMI1')
if [[ $my_laptop_external_monitor = *connected* ]]; then xrandr --auto --output HDMI1 --mode 1920x1080 --right-of eDP1

    fi
bspc monitor eDP1 -d 1 2 3 4 5 
bspc monitor HDMI1 -d  6 7 8 9 0

bspc config border_width        4
bspc config window_gap          -3
bspc config top_padding 	-4	
bspc config bottom_padding      -2
bspc config normal_border_color "#000000"
bspc config focused_border_color "#87AF87"
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

killall -q polybar
# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar example &
polybar top_external &

